"""Add created_at_jenkins column

Revision ID: 8f8ffc22496b
Revises: 1f90c62fd29f
Create Date: 2025-06-25 12:29:08.229577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8ffc22496b'
down_revision: Union[str, None] = '1f90c62fd29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jenkins_builds', sa.Column('created_at_jenkins', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jenkins_builds', 'created_at_jenkins')
    # ### end Alembic commands ###
